server:
  port: 6996

spring:
  application:
    name: demo-api
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${env.spring.datasource}/demo?useUnicode=yes&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
jwt:
  secret:
    key: Your-key-secret
  time:
    expiration: 80000000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${env.spring.datasource}/demo?useUnicode=yes&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8

env:
  spring:
    datasource: 127.0.0.1
  host:
    ip: localhost
    scheme: http